### ISSUE TITLE
Loading multiple bookmarks results in some pages getting stuck on HTTPS error screens

### ISSUE THREAD

**Issue by Gitoffthelawn** [claustromaniac/httpz#16]
I tried creating a bunch of bookmarks for sites that I know don't work with HTTPS.  I then loaded all the bookmarks at once (about 15 of them) with HTTPZ 0.7.1 enabled.

The result was that the following sites get redirected to HTTPS by HTTPZ, but never get redirected back to HTTP when they fail HTTPS:

http://blog.bahraniapps.com/gifcam/
http://liwi.io/
http://recordit.co/
http://www.onyxbits.de/

**Comment by claustromaniac** [comment]
I figured it out. The problem is specifically with timeout errors. I can fix it but not universally, because if someone **increases** the values of timeout settings in about:config, they will start running into that issue.

**Comment by claustromaniac** [comment]
Let me know if `0.7.2` doesn't solve the issue for you, and I'll reopen.

**Comment by Gitoffthelawn** [comment]
Unfortunately, `0.7.2` didn't solve it.  No difference in the final results.

BTW, it seemed like loading the HTTP bookmarks took longer than with `0.7.1`, but I didn't time it, so maybe I was just hungry or something. ;)

**Comment by claustromaniac** [comment]
Strange. I can't reproduce that anymore on my end.

Could you please follow the steps I described in [this comment](https://github.com/claustromaniac/httpz/issues/2#issuecomment-452064634)? The only difference is that the log entries no longer start with `Error info`, but with `HTTPZ` as in `HTTPZ: some error`.

Also, does the same happen if you try that with a clean profile?

**Comment by Gitoffthelawn** [comment]
Sorry I didn't get a chance to test this for you.  So busy lately.

If it comes up as an issue for you or anyone else, you can re-open and I'll see the issue.  If that happens, hopefully I'll have time to do some testing in the future.

**Comment by claustromaniac** [comment]
> Sorry I didn't get a chance to test this for you.

Don't worry! 😁
