### ISSUE TITLE
what's up with AMO reporting add-ons as 'recently updated'?

### ISSUE THREAD

**Issue by atomGit** [claustromaniac/httpz#25]
HTTPZ for example is at v0.7.2 released 13 days ago, yet it appears 2nd in the list (as of this writing) on AMO if you sort extensions by 'recently updated'...

https://addons.mozilla.org/en-US/firefox/search/?sort=updated&type=extension

you know what's up with that? i'm seeing this with other add-ons as well

**Comment by claustromaniac** [comment]
See [here](https://github.com/claustromaniac/httpz/issues/10#issuecomment-486735825)

TL;DR: AMO takes into account beta releases (I made two a short while ago), even though they're not listed there (for downloading).

**Comment by atomGit** [comment]
i thought that might have something to do w it :)

thanks for clearing that up

**Comment by atomGit** [comment]
oh, wait wait wait .... forgot to send you a cookie - an oldie but a goodie...
https://www.youtube.com/watch?v=rKRWy0VEiYI
