### ISSUE TITLE
Sammobile.com issues using HTTPZ

### ISSUE THREAD

**Issue by dracuking** [claustromaniac/httpz#30]
On home page desktop mode, Click on Samsung Firmware's tab up top. When you enter a model number in the box and attempt to search, nothing happens. Disabling HTTPZ fixes issue. No issues with HTTPS Everywhere or Smart HTTPS.

**Comment by claustromaniac** [comment]
Thank you very much for reporting this. It was not a minor issue, but it was due to a silly oversight when implementing a fix for #24

**Comment by ancientvamp** [comment]
Works now :)
