### ISSUE TITLE
Sites that use Cloudflare's Rocket Loader don't work properly

### ISSUE THREAD

**Issue by z411** [claustromaniac/httpz#31]
Cloudflare's Rocket Loader lazy loading script won't work when HTTPZ is enabled and sites that use it like https://thehackernews.com/ won't work properly.

The error thrown in the console is:

```
 rocket-loader.min.js:1:9661: Error: Permission denied to access property "__rocketLoaderInlineHandlerProxy"
```

It might be related to this and might need a similar fix:
https://github.com/kanap0nta/QuickDrag-WE/issues/52

Creating a new issue because #2 is locked. Apologies if it's the wrong course of action.
Thank you for the extension.

**Comment by claustromaniac** [comment]
I can't reproduce this issue with the latest version `0.8.2`. I released it less than twelve hours ago to address #30

Have you updated to `0.8.2` yet?

**Comment by z411** [comment]
Hi, thanks for the quick answer. Indeed 0.8.2 fixed it. For some reason I had to update the extension manually even though I had automatic updates enabled. Sorry and thanks again for your work.

**Comment by claustromaniac** [comment]
Great! Thank you for your feedback, anyway. I'm sure it would've taken me forever to notice this bug if @eldervamp and you hadn't reported these issues.

Just FYI, it takes a while for the auto updates to happen. If I recall correctly, Firefox checks for updates at a 24-hour interval by default, or so.
