### ISSUE TITLE
"Oops, Log in to network, etc."

### ISSUE THREAD

**Issue by eleius** [claustromaniac/httpz#34]
I'm using Httpz in "automatic mode". When visiting several http sites I have bookmarked (for example: http://www.easysurf.cc/scintd.htm), I briefly see an error page with the following lines before seeing the correct page:

Oops.
Log in to network
Hmm. We’re having trouble finding that site.
File not found
Access to the file was denied
Hmm. That address doesn’t look right.
The address wasn’t understood
etc...

It only happens the first time I visit a website.

I searched and saw something similar reported at https://github.com/claustromaniac/httpz/issues/2

**Comment by Madis0** [comment]
> When the initial request over HTTPS results in an error, Firefox starts loading an internal page that describes the error. HTTPZ does not wait for Firefox to finish loading those error pages, it immediately retries the request over HTTP, which causes them to load partially, and it does not look good. This is only a cosmetic issue, and a negligible one at that.

[readme.md](https://github.com/claustromaniac/httpz/blob/master/readme.md)

**Comment by eleius** [comment]
Well, I thought the error page was a custom one and that it could be simply bypassed when automatic mode is on. But re-reading that paragraph it says it's an internal one used by Firefox, so I guess the author can't do much about it. Nevermind then.

**Comment by claustromaniac** [comment]
For what it's worth, with auto mode off (AKA manual mode), you never get to see these, because the error page displayed by this extension (in manual mode) loads immediately.
