### ISSUE TITLE
Server-initiated redirections to HTTP are not intercepted

### ISSUE THREAD

**Issue by Madis0** [claustromaniac/httpz#36]
Opening https://http.badssl.com makes the server redirect to HTTP (status code 301), but HTTPZ does not intercept the redirection. Why?

Tried with HTTPZ 0.9.3 using settings
1. Automatic, intercept, handle, remember
2. Intercept, handle, remember
3. Intercept, handle (secure sites forgotten)
4. Intercept
5. Automatic, intercept
6. Automatic, intercept, handle

**Comment by claustromaniac** [comment]
I can't reproduce this (i.e. the extension works as intended on my end). Are you sure that site is not already in your ignore list? Use the export feature to check.

**Comment by Madis0** [comment]
Indeed, the site was on the ignore list. Thanks!
