### ISSUE TITLE
Preference saving problem

### ISSUE THREAD

**Issue by rampaa** [claustromaniac/httpz#38]
When I set "When a site does not support HTTPS, ignore requests to it..." to 10 days (or more) and click the save button, save button becomes ❌ instead of ✔ and does not save my preferences.

HTTPZ Version: 0.9.3
Firefox version: 69.0.3
OS: Windows 10

**Comment by claustromaniac** [comment]
Fixed in version `0.9.4`. 

Thanks for reporting.
