### ISSUE TITLE
[FIXED] Skip *.onion

### ISSUE THREAD

**Issue by sergeevabc** [claustromaniac/httpz#41]
[This][1] is an example of Tor-based site which should not be routed to HTTPS, because Tor internal transfers are already encrypted. Currently Httpz makes it impossible to connect to such resources.

[1]: http://flibustahezeous3.onion/

**Comment by sergeevabc** [comment]
Temporary workaround (for wandering souls if any) is to use another [already patched][1] extension. 

[1]: https://github.com/balvin-perrie/http-to-https/issues/2

**Comment by claustromaniac** [comment]
Should be fixed from [`0.10.0b`](https://github.com/claustromaniac/httpz/releases) onwards.

**Comment by sergeevabc** [comment]
Works as expected now!
Thank you for a quick reply, sir.
