### ISSUE TITLE
0.11.0b3 about:addons preferences layout issue when extensions.htmlaboutaddons.inline-options.enabled is false

### ISSUE THREAD

**Issue by grahamperrin** [claustromaniac/httpz#47]
Re: https://github.com/claustromaniac/httpz/issues/39#issuecomment-559974250

With my heavily-extended everyday Firefox profile, the new layout appears as it should. 

With a test profile, HTTPZ 0.11.0b3 alone enabled, I got this: 

![image](https://user-images.githubusercontent.com/192271/69912684-af42f300-1424-11ea-9683-96c8c32daeab.png)

![image](https://user-images.githubusercontent.com/192271/69912695-cf72b200-1424-11ea-97c6-4f0d2ec8f6fe.png)

![image](https://user-images.githubusercontent.com/192271/69912698-dac5dd80-1424-11ea-814a-d63dadf6b5dd.png)

In this profile, `extensions.htmlaboutaddons.inline-options.enabled` was `false`. Making it `true` (a Firefox 71.0 default) worked around the issue. 

I don't know whether `extensions.htmlaboutaddons.inline-options.enabled` is (or will be) redundant …

**Comment by claustromaniac** [comment]
Should work in [`0.11.0b5`](https://github.com/claustromaniac/httpz/releases). Thanks :+1:

**Comment by grahamperrin** [comment]
Fix confirmed, thanks: 

![image](https://user-images.githubusercontent.com/192271/69972109-ee527080-1518-11ea-989f-d417b87c06b3.png)
