### ISSUE TITLE
Intercept, proceed: sometimes does not proceed

### ISSUE THREAD

**Issue by grahamperrin** [claustromaniac/httpz#48]
1. <strike>Disable </strike>Enable interception of server-initiated redirections to http
2. <strike>*maybe* also disable </strike>enable handling of non-standard redirections to http
3. visit <http://www.fuelly.com/car/nissan/elgrand_/2000>
4. **Proceed with redirection**

… at least twice I found version 0.11.0b7 not proceeding – IIRC just a blank white extensions page – but (sorry) I didn't take a screenshot <strike>and now I can't reproduce the behaviour. 

More specifically, I can not get this after step (3): 

![image](https://user-images.githubusercontent.com/192271/70148725-9d6c8480-169e-11ea-9193-6ce8f0fdfa05.png)</strike>

**Comment by claustromaniac** [comment]
Well, I'm leaving this open for a while to see if we can at least manage to reproduce it.

**Comment by grahamperrin** [comment]
> … I can not get this …

Well d'uh, Graham, you'll not get the interception page if your first step is to disable interception. Opening post corrected! 

----

Here, although I imagine that it will be difficult to reproduce: 


![2019-12-05 14:02:23 frame](https://user-images.githubusercontent.com/192271/70244398-3917f680-176c-11ea-9bb8-e7cb244ad884.png)

![2019-12-05 14:02:30 frame](https://user-images.githubusercontent.com/192271/70244396-387f6000-176c-11ea-99a3-d08ad19fbda4.png)

![2019-12-05 14:02:44 frame](https://user-images.githubusercontent.com/192271/70244394-387f6000-176c-11ea-837e-e25784cee844.png)

![2019-12-05 14:02:51 frame](https://user-images.githubusercontent.com/192271/70244391-37e6c980-176c-11ea-93bd-3d7943128a3e.png)

![2019-12-05 14:02:55 frame](https://user-images.githubusercontent.com/192271/70244390-37e6c980-176c-11ea-8e97-bcd40a78e2a4.png)

![2019-12-05 14:02:56 frame](https://user-images.githubusercontent.com/192271/70244389-374e3300-176c-11ea-873a-0b534a013bfd.png)

![2019-12-05 14:03:10 frame](https://user-images.githubusercontent.com/192271/70244385-36b59c80-176c-11ea-94b7-f403c35b7f87.png)

The screen recording from which those frames are taken: 

* `2019-12-05 13:55.mp4` https://put.re/player/Kjx8fXLf.mp4
* [2019-12-05 13:55.zip](https://github.com/claustromaniac/httpz/files/3927342/2019-12-05.13.55.zip)

Watch from 08:23 on the timeline for alternative (more exotic) steps to production of the issue – setting an inappropriate URL as the home page – although again, I doubt that it will be *consistently* reproducible in this way. 

HTH. 

It's a curiosity, doesn't smell like something that might be encountered through normal usage. Could be me thrashing things again; at one point during the recording I *did* pause for a minute or so (I didn't bother to pause at other times).

**Comment by claustromaniac** [comment]
I accidentally closed this, but version `0.11.1` might have fixed it.

**Comment by claustromaniac** [comment]
Finally got around to testing this, and I also noticed other minor issues in the process. 

I fixed them all in `0.11.3`. Thank you for reporting :+1: You deserve a cookie 🍪
