### ISSUE TITLE
Unstandard port gets turned into HTTPS and fails

### ISSUE THREAD

**Issue by Mikaela** [claustromaniac/httpz#9]
Attempting to access http://silta.piraatit.fi:61825/robots.txt turns it into https://silta.piraatit.fi:61825/robots.txt which errors. That port is [TeleIRC](https://github.com/FruitieX/TeleIRC) and port 443 is used by OpenSSH.

**Comment by cwchristerw** [comment]
I think this happens because port 443 is open and then httpz thinks https is available. If port 443 closed, then maybe this site works properly.

**Comment by cwchristerw** [comment]
Have you tried reloading the site again because when I used IcecatMobile + HTTPZ it started working after first failed attempt.

Before reload change https -> http if doesnt automatically show original address in address bar.
